chore: dev tests (#21)
Co-authored-by: Dawid Krajewski <dawid@devine.team>

diff --git a/.github/workflows/tests/integration_testing/sync.yml b/.github/workflows/tests/integration_testing/sync.yml
--- a/.github/workflows/tests/integration_testing/sync.yml
+++ b/.github/workflows/tests/integration_testing/sync.yml
@@ -34,7 +34,7 @@ jobs:
     uses: ./.github/workflows/android_build.yml
     secrets: inherit
     with:
-      skip_build: ${{ github.event.inputs.skip_build || inputs.skip_build || github.event.label.name == 'sherlo:sync:skip_build' }}
+      skip_build: ${{ github.event.inputs.skip_build == true || inputs.skip_build == true || github.event.label.name == 'sherlo:sync:skip_build' }}
       profile: 'preview'
 
   ## iOS
@@ -46,7 +46,7 @@ jobs:
     uses: ./.github/workflows/ios_build.yml
     secrets: inherit
     with:
-      skip_build: ${{ github.event.inputs.skip_build || inputs.skip_build || github.event.label.name == 'sherlo:sync:skip_build' }}
+      skip_build: ${{ github.event.inputs.skip_build == true || inputs.skip_build == true || github.event.label.name == 'sherlo:sync:skip_build' }}
       profile: 'preview'
 
   ## Sherlo
@@ -56,7 +56,7 @@ jobs:
     needs: [android_preview_build, ios_preview_build]
     strategy:
       matrix:
-        node-version: ${{ fromJson(github.event.inputs.test_all_nodes && '["18.18.0"]' || '["22.3.0", "21.7.3", "20.14.0", "19.9.0", "18.20.3", "17.9.1", "16.20.2", "15.14.0", "14.21.3", "13.14.0", "12.22.12", "11.15.0", "10.24.1"]') }}
+        node-version: ${{ fromJson(github.event.inputs.test_all_nodes && '["22.3.0", "21.7.3", "20.14.0", "19.9.0", "18.20.3", "17.9.1", "16.20.2", "15.14.0", "14.21.3", "13.14.0", "12.22.12", "11.15.0", "10.24.1"]' || '["18.18.0"]') }}
     steps:
       - uses: actions/checkout@v2
         with:
@@ -65,7 +65,7 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
-          node-version: ${{ matrix.node-version }}
+          node-version: '18.18.0' # Default version
 
       - name: Install dependencies
         run: yarn
@@ -87,10 +87,10 @@ jobs:
           name: ios
           path: examples/expo-example/builds/preview
 
-      - name: Echo Directory Path
-        run: |
-          echo "Directory Path: examples/expo-example/builds/preview"
-          ls -la examples/expo-example/builds/preview
+      - name: Set up Node.js for testing
+        uses: actions/setup-node@v2
+        with:
+          node-version: ${{ matrix.node-version }}
 
       - name: Run Sherlo Action
         uses: ./.
@@ -100,3 +100,22 @@ jobs:
           config: configs/sync.preview.json
         env:
           SHERLO_TOKEN: ${{ secrets.SHERLO_TOKEN_SYNC }}
+        continue-on-error: true # Continue even if this step fails
+        id: sherlo
+
+      - name: Record result
+        run: echo "sherlo_sync_result=${{ steps.sherlo.outcome }}" >> $GITHUB_ENV
+
+  fail_check:
+    name: Fail Check
+    runs-on: ubuntu-latest
+    needs: [run_sherlo_sync]
+    steps:
+      - name: Check for failures
+        run: |
+          if grep -q "failure" <<< "${{ needs.run_sherlo_sync.outputs.sherlo_sync_result }}"; then
+            echo "One or more instances failed"
+            exit 1
+          else
+            echo "All instances passed"
+          fi
