chore: device testing (#24)
Co-authored-by: Sherlo Bot <admin@sherlo.io>
Co-authored-by: Dawid Krajewski <dawid@devine.team>

diff --git a/.github/workflows/node_testing.yml b/.github/workflows/node_testing.yml
--- a/.github/workflows/node_testing.yml
+++ b/.github/workflows/node_testing.yml
@@ -1,17 +1,78 @@
 name: Node Testing
 
 on:
-  pull_request:
-    branches: [dev]
-    types: [labeled]
   workflow_call:
   workflow_dispatch:
 
 jobs:
-  run:
-    name: Run
+  run_sherlo_sync:
+    name: Run Sherlo in sync mode
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        node-version:
+          [
+            '22.3.0',
+            '21.7.3',
+            '20.14.0',
+            '19.9.0',
+            '18.20.3',
+            '17.9.1',
+            '16.20.2',
+            '15.14.0',
+            '14.21.3',
+            '13.14.0',
+            '12.22.12',
+            '11.15.0',
+            '10.24.1',
+          ]
     steps:
       - uses: actions/checkout@v2
         with:
           ref: ${{ github.ref }}
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: '18.18.0' # Default version
+
+      - name: Install dependencies
+        run: yarn
+
+      - name: Build dependencies
+        run: yarn switch-env:dev
+        env:
+          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
+
+      - name: Set up Node.js for testing
+        uses: actions/setup-node@v2
+        with:
+          node-version: ${{ matrix.node-version }}
+
+      - name: Run Sherlo Action
+        uses: ./.
+        with:
+          ios: examples/expo-example/builds/preview/ios.tar.gz
+          android: examples/expo-example/builds/preview/android.apk
+          config: configs/sync.preview.json
+        env:
+          SHERLO_TOKEN: ${{ secrets.SHERLO_NODE_TESTING_TOKEN }}
+        continue-on-error: true # Continue even if this step fails
+        id: sherlo
+
+      - name: Record result
+        run: echo "sherlo_sync_result=${{ steps.sherlo.outcome }}" >> $GITHUB_ENV
+
+  fail_check:
+    name: Fail Check
+    runs-on: ubuntu-latest
+    needs: [run_sherlo_sync]
+    steps:
+      - name: Check for failures
+        run: |
+          if grep -q "failure" <<< "${{ needs.run_sherlo_sync.outputs.sherlo_sync_result }}"; then
+            echo "One or more instances failed"
+            exit 1
+          else
+            echo "All instances passed"
+          fi
